### ISSUE TITLE
Collision Detection and resolution

### ISSUE THREAD

**Issue by Docter60** [flaccorice27/Game-V2#1]
You think [this](http://jonathanwhiting.com/tutorial/collision/) is a good method to use for collisions?

**Comment by flaccorice27** [comment]
Hmm I hadn't thought about incremental movement but it seems like it could work well for what we're doing. You just temp move one pixel at a time and check after each time if you've collided and if you have just go back one step and cease movement

**Comment by flaccorice27** [comment]
If we're gonna do this then we will need to implement better detection for what tiles an object could be colliding with. You can't check the entire terrain 5 times per frame per entity

**Comment by Docter60** [comment]
Hmm...What if there was an algorithm that determines all tiles an entity is on top of just by using the entity's position/corners?  The map would probably have to be rectangular.
![picture](https://user-images.githubusercontent.com/11632779/27265922-ef0251a2-5469-11e7-9450-0488e807cdba.png)

**Comment by flaccorice27** [comment]
Well I think as long as the player cannot go on tiles that "don't exist" ie its position is not somewhere where there isnt a tile, then you can just calculate what tiles it is currently touching and then just directly access them in terrain.tiles, since it is structured in row-column format. I don't think it needs to be rectangular because like I said you just prevent the player from going "out of bounds" by surrounding the map with solid tiles. Then it doesnt matter if it is rectangular because you know you can directly access the tiles in the list of lists, because you know it must exist

**Comment by Docter60** [comment]
I'm just concerned about indexing correctly in the list of tiles, otherwise i dunno how to use the thing i drew above.

**Comment by flaccorice27** [comment]
well you just take the player's x, round it to the nearest multiple of 32, then divide it by 32 to get your "tile x", then get your "tile y", and index into terrain.tiles with tiles.get(tile-y).get(tile-x). And then you'd have to do that for all the tiles the player is touching. So like if his width is 32 then you check the next column, if his height is 64 you check the next two rows (so 2 columns, 3 rows, 6 tiles touched at any point), etc

**Comment by Docter60** [comment]
Is rounding to a multiple then dividing faster than dividing by 32 then flooring the number?

**Comment by flaccorice27** [comment]
dunno same result tho so it doesnt really matter

**Comment by Docter60** [comment]
BUT do you think this will work out fine
